### ISSUE TITLE
Codecov fails

### ISSUE THREAD

**Issue by AshlinHarris** [bcbi/PreprocessMD.jl#138]
Codecov gives the following error message: `There was a problem getting the source code from your provider. Unable to show line by line coverage.` I'm not sure if there is a way to show what code lines are uncovered, so this might have to be checked manually.

This is possibly related to the issue in pull request #136

**Comment by DilumAluthge** [comment]
I can't reproduce this. When I go to https://app.codecov.io/gh/bcbi/PreprocessMD.jl/blob/main/src/PreprocessMD.jl, I can see the coverage information just fine.

Are you logged into the Codecov website? Generally, you need to be logged in to Codecov in order to browse source code.

To log in, go to https://app.codecov.io/login/gh and click on the "Login with GitHub" button.

If that doesn't work, you can try it in an Incognito or Private Browsing window.

**Comment by AshlinHarris** [comment]
You're right, I'm able to view coverage whether I'm logged in or not.
